language: node_js

node_js:
  - "0.12.7"

before_install:
  - npm install -g gulp bower
  - npm install  eslint eslint-plugin-angular
install:
  - npm install
  - bower install

after_script:
  - gulp build:dev
